### PR TITLE
Add CI for Unity

### LINKED ISSUE #24: 0.2 - Add CI

### PR DESCRIPTION
**Pull request by MelvinCou**
Closes #24 

- Automatic comment to get APK from merge request easily
- Pre-release on merge on main

### CODE REVIEW

**Comment by MelvinCou** [comment]
🚀 Android APK available at: https://github.com/MelvinCou/Enigma-Stack/actions/runs/11953580926

**Comment by MelvinCou** [comment]
🚀 Android APK available at: https://github.com/MelvinCou/Enigma-Stack/actions/runs/11954178805

**Comment by MelvinCou** [comment]
🚀 Android APK available at: https://github.com/MelvinCou/Enigma-Stack/actions/runs/11954345373

**Review by MeloLawson — APPROVED** [review]
Good job !

**Review by MeloLawson — APPROVED** [review]
Good job !

**Comment by MelvinCou** [comment]
🚀 Android APK available at: https://github.com/MelvinCou/Coffee-Show-Up/actions/runs/11969188600

**Pull request merged**
